# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dt7LP6XhWILY90WMeTJkVkV7xLELT9Q-
"""

l1 = [int(x) for x in input("Enter a list of numbers separated by spaces: ").split()]

